# Generated by Django 2.2.7 on 2019-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
