# Generated by Django 2.2.7 on 2019-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191126_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('port', models.CharField(max_length=10, verbose_name='端口号')),
                ('name', models.CharField(max_length=50, verbose_name='主机名')),
                ('hostDesc', models.CharField(max_length=200, verbose_name='主机描述')),
            ],
        ),
    ]
